name: Python CI/CD Workflow

on:
  push:
    branches:
      - main
      - spark
  pull_request:
    branches:
      - main
      - spark

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Cache Python Dependencies
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 3: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          set -e
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      # Step 5: Set AWS Credentials from Secrets
      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          set -e
          echo "AWS_ACCESS_KEY=${AWS_ACCESS_KEY:0:4}********"
          echo "AWS_SECRET_KEY=${AWS_SECRET_KEY:0:4}********"

      # Step 6: Export PYTHONPATH
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      # Step 7: Train Model or Mock Model Directory
      - name: Prepare Model Directory
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          set -e
          source venv/bin/activate
          if [ -f "src/train_rf_tuning.py" ]; then
            python src/train_rf_tuning.py
          else
            mkdir -p models/tuned_rf_model
            echo "metadata" > models/tuned_rf_model/metadata
            echo "part-00000" > models/tuned_rf_model/part-00000
          fi

      # Step 8: Run linting with pylint
      - name: Lint Code
        run: |
          set -e
          source venv/bin/activate
          pylint src tests

      # Step 9: Run tests with pytest
      - name: Run Tests
        run: |
          set -e
          source venv/bin/activate
          pytest tests/ --junitxml=pytest-report.xml

      # Step 10: Upload test results (optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest-report.xml
